apiVersion: apps/v1
kind: Deployment
metadata:
  name: uideploy
  labels:
    app: uideploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uideploy
  template:
    metadata:
      labels:
        app: uideploy
    spec:
      containers:
      - name: uideploy
        image: druvakumarraini/uik8sdeploy
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: uideploy
  labels:
    app: uideploy
spec: 
  selector:
    app: uideploy
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
